sudo: required
os: linux
dist: xenial
service:
- docker
env:
  global:
  - MY_NAME=travis-ci
  - MY_TARGET_DIST=ubuntu:18.04
  - MY_MODE="cpp"
  - MY_TARGET_MOUNT=/tell/emp-env
before_install:
- docker pull $MY_TARGET_DIST
- docker run --name $MY_NAME -v $TRAVIS_BUILD_DIR:$MY_TARGET_MOUNT -td $MY_TARGET_DIST /bin/bash
- docker exec -ti $MY_NAME bash -c "apt update" > /dev/null
- docker exec -ti $MY_NAME bash -c "apt install -y software-properties-common" > /dev/null
- docker exec -ti $MY_NAME bash -c "apt update" > /dev/null
- docker exec -ti $MY_NAME bash -c "apt install -y cmake git build-essential libssl-dev libgmp-dev python libboost-dev libboost-{chrono,log,program-options,date-time,thread,system,filesystem,regex,test}-dev" > /dev/null
- docker exec -ti $MY_NAME bash -c "cmake --version"
install:
- docker exec -ti $MY_NAME bash -c "cd $MY_TARGET_MOUNT; ./build_emp-pvc.sh check"
script:
- docker exec -ti $MY_NAME bash -c "cd $MY_TARGET_MOUNT/emp-pvc/bin; ./test_pvc.cpp_exe aes alice & ./test_pvc.cpp_exe aes bob"
notifications:
  on_success: change
  on_failure: always
# vim: set expandtab shiftwidth=2 softtabstop=2 :
